# Generated by Django 6.0.6 on 2026-06-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('email', models.EmailField(help_text='University email address (e.g., student@university.edu)', max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, help_text='Display name shown to other users', max_length=150, verbose_name='full name')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture (optional)', null=True, upload_to='avatars/', verbose_name='avatar')),
                ('avatar_url', models.URLField(blank=True, help_text='External URL for avatar (if not using uploaded file)', max_length=500, verbose_name='avatar URL')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description', max_length=500, verbose_name='bio')),
                ('university_domain', models.CharField(blank=True, help_text='Normalized email domain (e.g., utm.my)', max_length=100, verbose_name='university domain')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from 1.00 to 5.00', max_digits=3, verbose_name='average rating')),
                ('total_transactions', models.PositiveIntegerField(default=0, help_text='Total number of completed transactions', verbose_name='total transactions')),
                ('reported_count', models.PositiveIntegerField(default=0, help_text='Number of times this user has been reported', verbose_name='reported count')),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notification_enabled', models.BooleanField(default=True, help_text='Receive push notifications', verbose_name='notifications enabled')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', help_text='Application theme preference', max_length=10, verbose_name='theme')),
                ('language', models.CharField(choices=[('en', 'English'), ('ms', 'Bahasa Melayu'), ('zh', '中文')], default='en', help_text='Application language', max_length=5, verbose_name='language')),
            ],
            options={
                'verbose_name': 'user settings',
                'verbose_name_plural': 'user settings',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['university_domain'], name='users_custo_univers_05a760_idx'),
        ),
    ]
