# Generated by Django 6.0.6 on 2026-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_message', 'New Message'), ('offer_update', 'Offer Update'), ('transaction_update', 'Transaction Update')], help_text='Type of notification event', max_length=30, verbose_name='type')),
                ('content', models.TextField(help_text='Notification message body', max_length=500, verbose_name='content')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has seen this notification', verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
