# Generated by Django 6.0.6 on 2026-06-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Optional: the item this chat is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='items.item', verbose_name='item'),
        ),
    ]
