# Generated by Django 6.0.6 on 2026-06-10 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Textbooks, Electronics)', max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g., textbooks)', max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added at')),
            ],
            options={
                'verbose_name': 'wishlist item',
                'verbose_name_plural': 'wishlist items',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Item title/name', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item', max_length=2000, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in local currency', max_digits=10, verbose_name='price')),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair')], default='good', help_text='Physical condition of the item', max_length=20, verbose_name='condition')),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs for this listing', verbose_name='images')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending')], default='available', help_text='Current listing status', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ['-created_at'],
            },
        ),
    ]
