# Generated by Django 6.0.6 on 2026-06-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='items.item', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='items_item_status_819478_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['condition'], name='items_item_conditi_5ed149_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='items_item_categor_ac6954_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['seller'], name='items_item_seller__493742_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-created_at'], name='items_item_created_3eaa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price'], name='items_item_price_cb7806_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['user', 'item'], name='items_wishl_user_id_8e0d44_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_user_wishlist_item'),
        ),
    ]
