# Generated by Django 5.2.15 on 2026-06-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this item was soft-deleted', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who soft-deleted this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag for admin moderation', verbose_name='is deleted'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_deleted'], name='items_item_is_dele_79eaf1_idx'),
        ),
    ]
