// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8hxT93w_cRAr5EZ0hEXZsbd56ISdB0E',
    appId: '1:891739966810:web:e65109298b4998f9fa7763',
    messagingSenderId: '891739966810',
    projectId: 'uniswap-utm-38aea',
    authDomain: 'uniswap-utm-38aea.firebaseapp.com',
    storageBucket: 'uniswap-utm-38aea.firebasestorage.app',
    measurementId: 'G-WGJQ5XWFMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn8pCAar1elOgWwufTvGj9nx_zj8g0zSQ',
    appId: '1:891739966810:android:d223074cdeaf1127fa7763',
    messagingSenderId: '891739966810',
    projectId: 'uniswap-utm-38aea',
    storageBucket: 'uniswap-utm-38aea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvR4vEKY5brMsH6uL38Awe85EdWltgDLk',
    appId: '1:891739966810:ios:7c70980bd8892d60fa7763',
    messagingSenderId: '891739966810',
    projectId: 'uniswap-utm-38aea',
    storageBucket: 'uniswap-utm-38aea.firebasestorage.app',
    iosBundleId: 'com.uniswap.uniswap',
  );
}
